# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import other98_pb2 as other98__pb2


class TheOther98Stub(object):
  """TheOther98 service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFeed = channel.unary_unary(
        '/other98.TheOther98/GetFeed',
        request_serializer=other98__pb2.FeedRequest.SerializeToString,
        response_deserializer=other98__pb2.FeedResponseView.FromString,
        )
    self.GetPost = channel.unary_unary(
        '/other98.TheOther98/GetPost',
        request_serializer=other98__pb2.GetRequest.SerializeToString,
        response_deserializer=other98__pb2.PostView.FromString,
        )
    self.GetProfile = channel.unary_unary(
        '/other98.TheOther98/GetProfile',
        request_serializer=other98__pb2.GetRequest.SerializeToString,
        response_deserializer=other98__pb2.ProfileResponseView.FromString,
        )
    self.CreatePost = channel.unary_unary(
        '/other98.TheOther98/CreatePost',
        request_serializer=other98__pb2.CreatePostRequest.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.CreateComment = channel.unary_unary(
        '/other98.TheOther98/CreateComment',
        request_serializer=other98__pb2.Comment.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.VoteOnPost = channel.unary_unary(
        '/other98.TheOther98/VoteOnPost',
        request_serializer=other98__pb2.PostVote.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.VoteOnComment = channel.unary_unary(
        '/other98.TheOther98/VoteOnComment',
        request_serializer=other98__pb2.CommentVote.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.GetMyConversations = channel.unary_stream(
        '/other98.TheOther98/GetMyConversations',
        request_serializer=other98__pb2.GetRequest.SerializeToString,
        response_deserializer=other98__pb2.ConversationView.FromString,
        )
    self.GetConversation = channel.unary_unary(
        '/other98.TheOther98/GetConversation',
        request_serializer=other98__pb2.GetRequest.SerializeToString,
        response_deserializer=other98__pb2.ConversationView.FromString,
        )
    self.GetMessagesInConversation = channel.unary_stream(
        '/other98.TheOther98/GetMessagesInConversation',
        request_serializer=other98__pb2.GetMessagesInConversationRequest.SerializeToString,
        response_deserializer=other98__pb2.MessageView.FromString,
        )
    self.GetNotifications = channel.unary_stream(
        '/other98.TheOther98/GetNotifications',
        request_serializer=other98__pb2.GetRequest.SerializeToString,
        response_deserializer=other98__pb2.NotificationBacklog.FromString,
        )
    self.CreateConversation = channel.unary_unary(
        '/other98.TheOther98/CreateConversation',
        request_serializer=other98__pb2.CreateConversationRequest.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.SendMessage = channel.unary_unary(
        '/other98.TheOther98/SendMessage',
        request_serializer=other98__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=other98__pb2.Result.FromString,
        )
    self.PopulateDatabase = channel.unary_unary(
        '/other98.TheOther98/PopulateDatabase',
        request_serializer=other98__pb2.Void.SerializeToString,
        response_deserializer=other98__pb2.Void.FromString,
        )


class TheOther98Servicer(object):
  """TheOther98 service definition.
  """

  def GetFeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateComment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoteOnPost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoteOnComment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyConversations(self, request, context):
    """chat
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConversation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMessagesInConversation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNotifications(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateConversation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PopulateDatabase(self, request, context):
    """demo methods
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TheOther98Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFeed': grpc.unary_unary_rpc_method_handler(
          servicer.GetFeed,
          request_deserializer=other98__pb2.FeedRequest.FromString,
          response_serializer=other98__pb2.FeedResponseView.SerializeToString,
      ),
      'GetPost': grpc.unary_unary_rpc_method_handler(
          servicer.GetPost,
          request_deserializer=other98__pb2.GetRequest.FromString,
          response_serializer=other98__pb2.PostView.SerializeToString,
      ),
      'GetProfile': grpc.unary_unary_rpc_method_handler(
          servicer.GetProfile,
          request_deserializer=other98__pb2.GetRequest.FromString,
          response_serializer=other98__pb2.ProfileResponseView.SerializeToString,
      ),
      'CreatePost': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePost,
          request_deserializer=other98__pb2.CreatePostRequest.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'CreateComment': grpc.unary_unary_rpc_method_handler(
          servicer.CreateComment,
          request_deserializer=other98__pb2.Comment.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'VoteOnPost': grpc.unary_unary_rpc_method_handler(
          servicer.VoteOnPost,
          request_deserializer=other98__pb2.PostVote.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'VoteOnComment': grpc.unary_unary_rpc_method_handler(
          servicer.VoteOnComment,
          request_deserializer=other98__pb2.CommentVote.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'GetMyConversations': grpc.unary_stream_rpc_method_handler(
          servicer.GetMyConversations,
          request_deserializer=other98__pb2.GetRequest.FromString,
          response_serializer=other98__pb2.ConversationView.SerializeToString,
      ),
      'GetConversation': grpc.unary_unary_rpc_method_handler(
          servicer.GetConversation,
          request_deserializer=other98__pb2.GetRequest.FromString,
          response_serializer=other98__pb2.ConversationView.SerializeToString,
      ),
      'GetMessagesInConversation': grpc.unary_stream_rpc_method_handler(
          servicer.GetMessagesInConversation,
          request_deserializer=other98__pb2.GetMessagesInConversationRequest.FromString,
          response_serializer=other98__pb2.MessageView.SerializeToString,
      ),
      'GetNotifications': grpc.unary_stream_rpc_method_handler(
          servicer.GetNotifications,
          request_deserializer=other98__pb2.GetRequest.FromString,
          response_serializer=other98__pb2.NotificationBacklog.SerializeToString,
      ),
      'CreateConversation': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConversation,
          request_deserializer=other98__pb2.CreateConversationRequest.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=other98__pb2.SendMessageRequest.FromString,
          response_serializer=other98__pb2.Result.SerializeToString,
      ),
      'PopulateDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.PopulateDatabase,
          request_deserializer=other98__pb2.Void.FromString,
          response_serializer=other98__pb2.Void.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'other98.TheOther98', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
